package com.company.employeemanagement.ai.rag.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * A single chunk of text extracted from a {@link KnowledgeDocument}.
 *
 * <p>Documents are split into overlapping, word-boundary-aligned chunks so that
 * retrieval can return focused passages rather than entire documents.
 * {@code chunkIndex} records the zero-based position of this chunk in the
 * parent document's ordered chunk list.
 *
 * <p>This entity does NOT extend {@link com.company.employeemanagement.entity.BaseEntity}
 * because chunks do not need {@code createdBy}/{@code updatedBy} auditing — they are
 * system-generated and never mutated after initial ingestion.
 *
 * @author Employee Management Portal Team
 */
@Entity
@Table(name = "knowledge_chunks")
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class KnowledgeChunk {

    /**
     * UUID primary key, generated by Hibernate.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(name = "id", nullable = false, updatable = false, length = 36)
    private UUID id;

    /**
     * The parent document this chunk belongs to.
     * Loaded lazily to avoid N+1 queries when listing chunks.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "document_id", nullable = false)
    private KnowledgeDocument document;

    /**
     * Zero-based sequential index of this chunk within the parent document.
     */
    @Column(name = "chunk_index", nullable = false)
    private int chunkIndex;

    /**
     * The actual chunk text content.
     */
    @Column(name = "content", nullable = false, columnDefinition = "TEXT")
    private String content;

    /**
     * Approximate number of tokens in this chunk (estimated as word count).
     * Used for size-budgeting when assembling context windows.
     */
    @Column(name = "token_count")
    private Integer tokenCount;

    /**
     * Optional JSON string carrying arbitrary metadata about this chunk
     * (e.g., page number, section heading).
     */
    @Column(name = "metadata", columnDefinition = "TEXT")
    private String metadata;

    /**
     * Timestamp when this chunk was created.
     */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when this chunk was last updated.
     */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
}
