package com.company.employeemanagement.entity.enums;

/**
 * Types of in-app notifications generated by the system.
 *
 * @author Employee Management Portal Team
 */
public enum NotificationType {

    /** Sent to an employee when a task has been assigned to them. */
    TASK_ASSIGNED,

    /** Sent to the task creator/manager when an employee starts a task. */
    TASK_STARTED,

    /** Sent to the task creator/manager when an employee submits a task for review. */
    TASK_SUBMITTED,

    /** Sent to the employee when a manager approves their submission. */
    TASK_APPROVED,

    /** Sent to the employee when a manager requests changes on their submission. */
    TASK_CHANGES_REQUESTED,

    /** Sent when a task's status changes (general). */
    TASK_STATUS_CHANGED,

    /** Sent when a task is approaching its due date (within 24h or 2h). */
    TASK_DUE_SOON,

    /** Sent when a task is past its due date. */
    TASK_OVERDUE,

    /** Sent to the original and new assignee when a task is reassigned. */
    TASK_REASSIGNED,

    /** Sent when a new comment is posted on a task (to the other party). */
    TASK_COMMENT,

    /** Sent to the assigned employee when meaningful task fields are updated by a manager. */
    TASK_UPDATED,

    /**
     * Sent to the employee when a manager/HR/admin approves their leave request.
     * This is a positive/success event; the frontend plays a happy sound.
     */
    LEAVE_APPROVED,

    /**
     * Sent to the employee when a manager/HR/admin rejects their leave request.
     * Includes the rejection reason in the notification message when provided.
     */
    LEAVE_REJECTED,

    /**
     * Sent to the employee when an administrator changes their role.
     * Only generated when the role actually changes.
     * This is a positive/success event; the frontend plays a happy sound.
     */
    ROLE_UPDATED,

    /**
     * Sent to the requesting manager/HR/admin when an AI task evaluation completes
     * successfully. Clicking the notification navigates to the task detail page.
     */
    AI_REVIEW_COMPLETED,

    /**
     * Sent to the requesting manager/HR/admin when an AI task evaluation fails.
     * Clicking the notification navigates to the task detail page.
     */
    AI_REVIEW_FAILED
}
