package com.company.employeemanagement.entity.enums;

/**
 * Types of in-app notifications generated by the system.
 *
 * @author Employee Management Portal Team
 */
public enum NotificationType {

    /** Sent to an employee when a task has been assigned to them. */
    TASK_ASSIGNED,

    /** Sent to the task creator/manager when an employee starts a task. */
    TASK_STARTED,

    /** Sent to the task creator/manager when an employee submits a task for review. */
    TASK_SUBMITTED,

    /** Sent to the employee when a manager approves their submission. */
    TASK_APPROVED,

    /** Sent to the employee when a manager requests changes on their submission. */
    TASK_CHANGES_REQUESTED,

    /** Sent when a task's status changes (general). */
    TASK_STATUS_CHANGED,

    /** Sent when a task is approaching its due date (within 24h or 2h). */
    TASK_DUE_SOON,

    /** Sent when a task is past its due date. */
    TASK_OVERDUE,

    /** Sent to the original and new assignee when a task is reassigned. */
    TASK_REASSIGNED,

    /** Sent when a new comment is posted on a task (to the other party). */
    TASK_COMMENT
}
